name: 'Chromatic Deployment'

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
