name: 'Chromatic Deployment'

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
      - develop

jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm install

      - name: Generate Environment Variables File for Production
        run: |
          echo "API_HOSTNAME=$API_HOSTNAME" >> .env
          echo "API_PORT=$API_PORT" >> .env
          echo "API_VERSION=$API_VERSION" >> .env
          echo "API_URL=$API_URL" >> .env
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID" >> .env
          echo "NEXT_PUBLIC_MSW=$NEXT_PUBLIC_MSW" >> .env
          echo "NEXT_PUBLIC_GOOGLE_REDIRECT_URI=$NEXT_PUBLIC_GOOGLE_REDIRECT_URI" >> .env
        env:
          API_HOSTNAME: ${{ secrets.API_HOSTNAME }}
          API_PORT: ${{ secrets.API_PORT }}
          API_VERSION: ${{ secrets.API_VERSION }}
          API_URL: ${{ secrets.API_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
          NEXT_PUBLIC_MSW: ${{ secrets.NEXT_PUBLIC_MSW }}
          NEXT_PUBLIC_GOOGLE_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI }}

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
